-- MySQL Script generated by MySQL Workbench
-- Fri Dec 29 00:11:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scango` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------
USE `scango` ;

-- -----------------------------------------------------
-- Table `scango`.`LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`LEVEL` ;

CREATE TABLE IF NOT EXISTS `scango`.`LEVEL` (
  `levelId` INT NOT NULL AUTO_INCREMENT,
  `levelName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`levelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`ACCOUNT` ;

CREATE TABLE IF NOT EXISTS `scango`.`ACCOUNT` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `gender` VARCHAR(45) NULL,
  `birthDate` DATETIME NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `createTime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `leveId_fk_idx` (`level` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  CONSTRAINT `levelId_fk`
    FOREIGN KEY (`level`)
    REFERENCES `scango`.`LEVEL` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`SERVICE` ;

CREATE TABLE IF NOT EXISTS `scango`.`SERVICE` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `serviceLocation` VARCHAR(45) NOT NULL,
  `serviceName` VARCHAR(45) NOT NULL,
  `serviceUrl` VARCHAR(100) NULL,
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`POSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`POSITION` ;

CREATE TABLE IF NOT EXISTS `scango`.`POSITION` (
  `positionId` INT NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`positionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `scango`.`PRODUCT` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `qrCode` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  `inventory` INT UNSIGNED NULL,
  `isLaunch` TINYINT(1) NULL,
  PRIMARY KEY (`productId`),
  INDEX `position_fk_idx` (`position` ASC) VISIBLE,
  CONSTRAINT `position_fk`
    FOREIGN KEY (`position`)
    REFERENCES `scango`.`POSITION` (`positionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`COUPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`COUPON` ;

CREATE TABLE IF NOT EXISTS `scango`.`COUPON` (
  `couponId` INT NOT NULL AUTO_INCREMENT,
  `couponName` VARCHAR(45) BINARY NOT NULL,
  `value` DOUBLE UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`couponId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`CART` ;

CREATE TABLE IF NOT EXISTS `scango`.`CART` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `couponId` INT NULL,
  `totalPrice` INT NOT NULL,
  PRIMARY KEY (`cartId`),
  INDEX `userId_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `cartCoupon_fk_idx` (`couponId` ASC) VISIBLE,
  CONSTRAINT `userId_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `scango`.`ACCOUNT` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartCoupon_fk`
    FOREIGN KEY (`couponId`)
    REFERENCES `scango`.`COUPON` (`couponId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`CARTITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`CARTITEM` ;

CREATE TABLE IF NOT EXISTS `scango`.`CARTITEM` (
  `cartId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `itemPrice` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cartId`, `productId`),
  INDEX `cartId_fk_idx` (`cartId` ASC) VISIBLE,
  INDEX `product_fk_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `cartId_fk`
    FOREIGN KEY (`cartId`)
    REFERENCES `scango`.`CART` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_fk`
    FOREIGN KEY (`productId`)
    REFERENCES `scango`.`PRODUCT` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`USER_COUPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`USER_COUPON` ;

CREATE TABLE IF NOT EXISTS `scango`.`USER_COUPON` (
  `userId` INT NOT NULL,
  `couponId` INT NOT NULL,
  PRIMARY KEY (`userId`, `couponId`),
  INDEX `couponId_fk_idx` (`couponId` ASC) VISIBLE,
  CONSTRAINT `couponId_fk`
    FOREIGN KEY (`couponId`)
    REFERENCES `scango`.`COUPON` (`couponId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `scango`.`ACCOUNT` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`LEVEL_REF_SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`LEVEL_REF_SERVICE` ;

CREATE TABLE IF NOT EXISTS `scango`.`LEVEL_REF_SERVICE` (
  `levelId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  PRIMARY KEY (`levelId`, `serviceId`),
  INDEX `serviceId_fk_idx` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `levelService_fk`
    FOREIGN KEY (`levelId`)
    REFERENCES `scango`.`LEVEL` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serviceId_fk`
    FOREIGN KEY (`serviceId`)
    REFERENCES `scango`.`SERVICE` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`MESSAGE` ;

CREATE TABLE IF NOT EXISTS `scango`.`MESSAGE` (
  `messageId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `message` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`messageId`),
  INDEX `message_fk_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `message_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `scango`.`ACCOUNT` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`FEEDBACK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`FEEDBACK` ;

CREATE TABLE IF NOT EXISTS `scango`.`FEEDBACK` (
  `userId` INT NOT NULL,
  `FEEDBACKcol` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `scango`.`ORDER` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `cartId` INT NOT NULL,
  `createTime` TIMESTAMP NULL,
  PRIMARY KEY (`orderId`),
  INDEX `userOrder_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `cartOrder_idx` (`cartId` ASC) VISIBLE,
  CONSTRAINT `userOrder_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `scango`.`ACCOUNT` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartOrder`
    FOREIGN KEY (`cartId`)
    REFERENCES `scango`.`CART` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
