DROP TABLE IF EXISTS `scango`.`CART` ;
DROP TABLE IF EXISTS `scango`.`USER_COUPON` ;
DROP TABLE IF EXISTS `scango`.`MESSAGE` ;
DROP TABLE IF EXISTS `scango`.`FEEDBACK` ;
DROP TABLE IF EXISTS `scango`.`ORDERITEM` ;
DROP TABLE IF EXISTS `scango`.`ORDERS` ;
DROP TABLE IF EXISTS `scango`.`ORDER` ;
DROP TABLE IF EXISTS `scango`.`ACCOUNT` ;
DROP TABLE IF EXISTS `scango`.`LEVEL_REF_SERVICE` ;
DROP TABLE IF EXISTS `scango`.`USER` ;
DROP TABLE IF EXISTS `scango`.`LEVEL` ;
DROP TABLE IF EXISTS `scango`.`SERVICE` ;
DROP TABLE IF EXISTS `scango`.`PRODUCT` ;
DROP TABLE IF EXISTS `scango`.`POSITION` ;
DROP TABLE IF EXISTS `scango`.`COUPON` ;
DROP TABLE IF EXISTS `scango`.`CATEGORY` ;

