-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 11:07:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scango` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------
USE `scango` ;

-- -----------------------------------------------------
-- Table `scango`.`USERINFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`USERINFO` ;

CREATE TABLE IF NOT EXISTS `scango`.`USERINFO` (
  `userName` VARCHAR(50) NOT NULL,
  `gender` VARCHAR(45) NULL,
  `birthDate` DATE NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`userName`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`LEVEL` ;

CREATE TABLE IF NOT EXISTS `scango`.`LEVEL` (
  `levelId'` INT NOT NULL AUTO_INCREMENT,
  `levelName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`levelId'`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`USER` ;

CREATE TABLE IF NOT EXISTS `scango`.`USER` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `createTime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  INDEX `level_fk_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `userName_fk`
    FOREIGN KEY (`userName`)
    REFERENCES `scango`.`USERINFO` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `level_fk`
    FOREIGN KEY (`level`)
    REFERENCES `scango`.`LEVEL` (`levelId'`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`POSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`POSITION` ;

CREATE TABLE IF NOT EXISTS `scango`.`POSITION` (
  `positionId` INT NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`positionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `scango`.`PRODUCT` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  `qrCode` VARCHAR(45) NOT NULL,
  `isLaunch` TINYINT(1) NULL,
  PRIMARY KEY (`productId`),
  INDEX `position_fk_idx` (`position` ASC) VISIBLE,
  CONSTRAINT `position_fk`
    FOREIGN KEY (`position`)
    REFERENCES `scango`.`POSITION` (`positionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`SERVICE` ;

CREATE TABLE IF NOT EXISTS `scango`.`SERVICE` (
  `serviceId` INT NOT NULL,
  `serviceLocation` VARCHAR(45) NOT NULL,
  `serviceName` VARCHAR(45) NOT NULL,
  `serviceUrl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`CART` ;

CREATE TABLE IF NOT EXISTS `scango`.`CART` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `isCheckout` TINYINT(1) NULL,
  `checkoutTime` DATETIME NULL,
  PRIMARY KEY (`cartId`),
  INDEX `userId_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userID`)
    REFERENCES `scango`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`CARTITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`CARTITEM` ;

CREATE TABLE IF NOT EXISTS `scango`.`CARTITEM` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `cartId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `cartId_fk_idx` (`cartId` ASC) VISIBLE,
  INDEX `productId_fk_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `cartId_fk`
    FOREIGN KEY (`cartId`)
    REFERENCES `scango`.`CART` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productId_fk`
    FOREIGN KEY (`productId`)
    REFERENCES `scango`.`PRODUCT` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scango`.`COUPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scango`.`COUPON` ;

CREATE TABLE IF NOT EXISTS `scango`.`COUPON` (
  `couponId` INT NOT NULL AUTO_INCREMENT,
  `couponName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`couponId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
