-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 16:09:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema scango
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEVEL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEVEL` (
  `levelId` INT NOT NULL,
  `levelName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`levelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `birthday` DATE NULL,
  `levelId` INT NULL DEFAULT 1,
  `authType` ENUM('ScanGo', 'Google') NULL DEFAULT 'ScanGo',
  `authId` VARCHAR(100) NULL,
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`),
  INDEX `leveId_fk_idx` (`levelId` ASC) VISIBLE,
  CONSTRAINT `levelId_fk`
    FOREIGN KEY (`levelId`)
    REFERENCES `mydb`.`LEVEL` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SERVICE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SERVICE` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `serviceLocation` VARCHAR(45) NOT NULL,
  `serviceName` VARCHAR(45) NOT NULL,
  `serviceUrl` VARCHAR(100) NULL,
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATEGORY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORY` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `categoryPart` VARCHAR(45) NOT NULL,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(255) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `categoryId` INT NOT NULL,
  `inventory` INT UNSIGNED NULL,
  `picture` VARCHAR(255) NULL,
  PRIMARY KEY (`productId`),
  INDEX `categoryId_fk_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `categoryId_fk`
    FOREIGN KEY (`categoryId`)
    REFERENCES `mydb`.`CATEGORY` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CART` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CART` (
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productQuantity` INT UNSIGNED NOT NULL,
  INDEX `userId_fk_idx` (`userId` ASC) VISIBLE,
  PRIMARY KEY (`userId`, `productId`),
  INDEX `cartProduct_fk_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `userId_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartProduct_fk`
    FOREIGN KEY (`productId`)
    REFERENCES `mydb`.`PRODUCT` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COUPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COUPON` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COUPON` (
  `couponId` INT NOT NULL AUTO_INCREMENT,
  `couponName` VARCHAR(45) BINARY NOT NULL,
  `value` DOUBLE UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`couponId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_COUPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_COUPON` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_COUPON` (
  `userId` INT NOT NULL,
  `couponId` INT NOT NULL,
  PRIMARY KEY (`userId`, `couponId`),
  INDEX `couponId_fk_idx` (`couponId` ASC) VISIBLE,
  CONSTRAINT `couponId_fk`
    FOREIGN KEY (`couponId`)
    REFERENCES `mydb`.`COUPON` (`couponId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LEVEL_REF_SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LEVEL_REF_SERVICE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LEVEL_REF_SERVICE` (
  `levelId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  PRIMARY KEY (`levelId`, `serviceId`),
  INDEX `serviceId_fk_idx` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `levelService_fk`
    FOREIGN KEY (`levelId`)
    REFERENCES `mydb`.`LEVEL` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serviceId_fk`
    FOREIGN KEY (`serviceId`)
    REFERENCES `mydb`.`SERVICE` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MESSAGE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MESSAGE` (
  `messageId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `message` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`messageId`),
  INDEX `message_fk_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `message_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDERS` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `couponId` INT NULL,
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `orderTotalPrice` INT UNSIGNED NULL,
  `discountTotalPrice` INT UNSIGNED NULL,
  `rating` INT UNSIGNED NULL,
  PRIMARY KEY (`orderId`),
  INDEX `userOrder_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `orderCoupon_fk_idx` (`couponId` ASC) VISIBLE,
  CONSTRAINT `userOrder_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderCoupon_fk`
    FOREIGN KEY (`couponId`)
    REFERENCES `mydb`.`COUPON` (`couponId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FEEDBACK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FEEDBACK` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FEEDBACK` (
  `userId` INT NOT NULL,
  `orderId` INT NOT NULL,
  `feedback` INT UNSIGNED NULL,
  PRIMARY KEY (`userId`, `orderId`),
  INDEX `orderFeedback_fk_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `userFeedback_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderFeedback_fk`
    FOREIGN KEY (`orderId`)
    REFERENCES `mydb`.`ORDERS` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORDERITEM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORDERITEM` (
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productPrice` INT UNSIGNED NOT NULL,
  `itemQuantity` INT UNSIGNED NOT NULL,
  `itemPrice` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderId`, `productId`),
  INDEX `productItem_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `orderId_fk`
    FOREIGN KEY (`orderId`)
    REFERENCES `mydb`.`ORDERS` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productItem`
    FOREIGN KEY (`productId`)
    REFERENCES `mydb`.`PRODUCT` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
